package sec1;
//NullPointerException
public class ExceptionExam2 {

	public static void main(String[] args) {
		String name = null;
		//실제 처리할 문장(try)이 예외가 발생하면, 예외처리 문장을 실행 
		try {
			//실제 처리할 문장
			System.out.println(name.toString());		 
		} catch(NullPointerException e) {
			//예외가 발생할 경우 처리할 문장 
			e.printStackTrace();
		} catch(Exception e) {
			System.out.println("알 수 없는 예외 발생");
		}


	}

}
